export { default as App } from "./App"
export { default as ErrorPage } from "./404"
export { default as About } from "./About"
export { default as Recruit } from "./Recruit"
export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as ProductDetails } from "./products/ProductDetail" ;
export { default as Products } from "./products/index"
export { default as Cart } from "./Cart"
export { default as Checkout } from "./Checkout"
export { default as MainAdminLayout } from "./admin/mainAdLayout"
export { default as Console } from "./admin/index"
export { default as AdminProducts } from "./admin/Products/index"
export {default as AdminAccounts} from "./admin/Accounts/index"
export {default as AdminCategories} from "./admin/Categories/index"
export {default as AdminOrders} from "./admin/Orders/index"
export { default as Profile } from "./Profile"
